[package]
name = "slowchop_console"
version = "0.1.0"
edition = "2021"

[dependencies]
slowchop_console_derive = { path = "../slowchop_console_derive" }
#bevy = { version = "0.12.0", features = ["dynamic_linking"]}
strum = { version = "0.25.0", features = ["derive"] }
nom = "7.1.3"
thiserror = "1.0.50"
shlex = "1.2.0"

